# **Exercicio Duelo de Modelos 4**

Nesta tarefa, vocês irão criar o seu próprio duelo de modelos, com o objetivo de superar os resultados apresentados em aula. O desafio é alcançar um desempenho superior ao que obtivemos, e para isso, será necessário aplicar todas as melhorias que vocês aprenderam ao longo dos módulos, utilizando a base de dados do Titanic.

**1. Escolha do Modelo:**
Selecione um dos modelos que foram explorados nos duelos de modelos ao longo do curso. Pode ser SVM, Random Forest, XGBoost, ou qualquer outro que tenhamos abordado.

**2. Aperfeiçoamento:**
**Aplique as técnicas que aprendemos para melhorar o desempenho do seu modelo:**

**Hiperparâmetros:** Utilize GridSearchCV ou RandomSearchCV para encontrar os melhores parâmetros.

**Cross Validation:** Avalie a robustez do modelo utilizando validação cruzada para garantir que ele generaliza bem.

**Balanceamento de Classes:** Se o seu modelo lida com problemas de classes desbalanceadas, explore técnicas como SMOTE, undersampling ou oversampling.

**Padronização e Normalização:** Lembre-se de padronizar os dados, especialmente se for usar modelos que são sensíveis à escala das variáveis.

**3. Submissão no Kaggle:**
Treine o seu modelo com os dados de treino e gere as previsões para os dados de teste. Lembre-se de que o conjunto de teste não possui a variável alvo (y_test), pois a avaliação será feita com base nas submissões no Kaggle.
Submeta suas previsões na competição do Titanic no Kaggle.

**4. Entrega:**
Envie o código que você desenvolveu, detalhando cada etapa do seu processo de modelagem, explicando as escolhas feitas e como essas ajudaram a melhorar o modelo.

Junto com o código, envie um print do seu score obtido na plataforma do Kaggle. Esse score será a sua métrica final de avaliação, mostrando como o seu modelo se compara com os demais.

**5. Competição Saudável:**
A ideia é trazer um senso de competição saudável, então não vale replicar exatamente o que fizemos na aula! Inove, explore novas combinações de parâmetros e técnicas, e mostre do que é capaz. O importante é exercitar o pensamento crítico e a capacidade de experimentar.

**Dicas Finais:**

Seja criativo e tenha um olhar crítico sobre o que pode ser melhorado.
Teste diferentes abordagens e não se prenda a um único caminho.
Lembre-se de que, mais do que alcançar o melhor score, o objetivo é aprender e aplicar o conhecimento de forma prática e eficaz.
Boa sorte! Estamos ansiosos para ver como cada um de vocês vai se sair nesse desafio e quais insights irão surgir dessa competição!

Ao final dessa atividade vocês terão participado da primeira competição publica de ciência de dados de vocês = )

In [181]:
from sklearn.svm import SVC
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [182]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [118]:
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Conhecendo os nomes das variáveis e suas características.

In [6]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [7]:
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 36.1 KB

In [8]:
test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [9]:
test_df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [10]:
train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
train_df.duplicated().sum()

np.int64(0)

In [12]:
test_df.duplicated().sum()

np.int64(0)

Verificando valores nulos ou duplicados que odem atrapalhar o modelo.

In [ ]:
Optei por preencher com a média os valores nulos de idade pois são grande parte da amostra.

In [183]:
train_df['Age'].fillna(train_df['Age'].mean(), inplace = True)

C:\Users\Regina\AppData\Local\Temp\ipykernel_2820\188655451.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_df['Age'].fillna(train_df['Age'].mean(), inplace = True)

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [184]:
test_df['Age'].fillna(test_df['Age'].mean(), inplace = True)

C:\Users\Regina\AppData\Local\Temp\ipykernel_2820\4136873691.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  test_df['Age'].fillna(test_df['Age'].mean(), inplace = True)

0      34.50000
1      47.00000
2      62.00000
3      27.00000
4      22.00000
         ...
413    30.27259
414    39.00000
415    38.50000
416    30.27259
417    30.27259
Name: Age, Length: 418, dtype: float64

In [185]:
test_df['Fare'].fillna(test_df['Fare'].mean(), inplace = True)

C:\Users\Regina\AppData\Local\Temp\ipykernel_2820\3877540087.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  test_df['Fare'].fillna(test_df['Fare'].mean(), inplace = True)

0        7.8292
1        7.0000
2        9.6875
3        8.6625
4       12.2875
         ...
413      8.0500
414    108.9000
415      7.2500
416      8.0500
417     22.3583
Name: Fare, Length: 418, dtype: float64

In [186]:
train_df['Sex'] = train_df['Sex'].map({'male':0,'female':1})

In [187]:
test_df['Sex'] = test_df['Sex'].map({'male':0,'female':1})

In [188]:
test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",0,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",1,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",0,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",0,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",1,22.0,1,1,3101298,12.2875,NaN,S

Tratamento para poder usar a variável sex no modelo.

In [189]:
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S

In [190]:
train_df= pd.get_dummies(train_df, columns =['Embarked'], prefix = 'Embarked')

Criação de uma nova variável mais simples para usar os dados sem prejudicar o modelo

In [191]:
test_df= pd.get_dummies(test_df, columns =['Embarked'], prefix = 'Embarked')

In [192]:
train_df['cabin_known'] = train_df['Cabin'].notna().astype(int)

In [193]:
test_df['cabin_known'] = test_df['Cabin'].notna().astype(int)

In [194]:
train_df= train_df.drop(columns=['Cabin'])

In [195]:
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S,cabin_known
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,False,False,True,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,True,False,False,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,False,False,True,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,False,False,True,1
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,False,False,True,0

In [196]:
test_df= test_df.drop(columns=['Cabin'])

In [197]:
test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S,cabin_known
0,892,3,"Kelly, Mr. James",0,34.5,0,0,330911,7.8292,False,True,False,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",1,47.0,1,0,363272,7.0000,False,False,True,0
2,894,2,"Myles, Mr. Thomas Francis",0,62.0,0,0,240276,9.6875,False,True,False,0
3,895,3,"Wirz, Mr. Albert",0,27.0,0,0,315154,8.6625,False,False,True,0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",1,22.0,1,1,3101298,12.2875,False,False,True,0

In [198]:
train_df = train_df.drop(columns=['Name','Ticket'])

Remoção e vari´veis que não serão usadas

In [199]:
variaveis =['Sex','cabin_known','Fare','Pclass']

separando em x e y e destacando que a plataforma não fornece ytest

In [200]:
x = train_df[variaveis]

In [201]:
y = train_df['Survived']

In [202]:
x_test = test_df[variaveis]

In [203]:
smote = SMOTE(random_state = 42)

In [204]:
x_train_balanced, y_train_balanced = smote.fit_resample(x,y)

Balanceando só o treino para ajudar o modelo e padronizando treino e teste

In [205]:
scaler = StandardScaler()

In [206]:
x_train_balanced_scaled = scaler.fit_transform(x_train_balanced)

In [207]:
x_test_scaled = scaler.transform(x_test)

In [208]:
print('Dps de balancear')
print(y_train_balanced.value_counts())

Dps de balancear
Survived
0    549
1    549
Name: count, dtype: int64

Definindo parametros

In [209]:
svm = SVC(kernel='linear', random_state=1)

In [210]:
param_grid_SVM = {
    'C':[0.1,1,10,100],
    'kernel':['linear', 'rbf']
}
grid_search_svm = GridSearchCV(
    estimator = svm, 
    param_grid = param_grid_SVM,
    scoring = 'accuracy',
    cv = 5,
    verbose = 2,
    n_jobs = -1,
    error_score='raise'
)

Treinando o modelo

In [211]:
grid_search_svm.fit(x_train_balanced_scaled, y_train_balanced)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(cv=5, error_score='raise',
             estimator=SVC(kernel='linear', random_state=1), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100], 'kernel': ['linear', 'rbf']},
             scoring='accuracy', verbose=2)

In [212]:
best_params = grid_search_svm.best_params_

In [213]:
best_svm_model = grid_search_svm.best_estimator_

In [214]:
y_pred_svm= best_svm_model.predict(x_train_balanced_scaled)

In [215]:
print(best_params)

{'C': 100, 'kernel': 'rbf'}

In [216]:
relatorio = classification_report(y_train_balanced,y_pred_svm)

In [217]:
print(relatorio)

              precision    recall  f1-score   support

           0       0.79      0.81      0.80       549
           1       0.80      0.79      0.80       549

    accuracy                           0.80      1098
   macro avg       0.80      0.80      0.80      1098
weighted avg       0.80      0.80      0.80      1098

Modelo com boa acurácia 0.80 indicando que a proporção de previsões corretas em relação ao total de previsões feitas é de 80%. f1 score também de 0.80 mostrando um desempenho equilibrado na previsão das classes.

In [218]:
nan_rows = x_test.isna().any(axis=1)
print(x_test[nan_rows])

     Sex  cabin_known  Fare  Pclass
152    0            0   NaN       3

In [ ]:
Identificando e preenchendo com a média um valor de nan na coluna Fare que impediu o modelo de continuar

In [219]:
linha, coluna = np.argwhere(np.isnan(x_test_scaled))[0]

print("Linha:", linha)
print("Coluna:", coluna)
print("Valor original:", x_test.iloc[linha, coluna])
print("Variável:", x_test.columns[coluna])

Linha: 152
Coluna: 2
Valor original: nan
Variável: Fare

In [220]:
fare_col = 2
fare_median = np.nanmedian(x_test_scaled[:, fare_col])
x_test_scaled[152, fare_col] = fare_median
print("NaN restantes:", np.isnan(x_test_scaled).sum())

NaN restantes: 0

In [176]:
print("NaN em x_test_scaled:", np.isnan(x_test_scaled).sum())

NaN em x_test_scaled: 0

In [166]:
print("NaN em x_test_scaled:", np.isnan(x_test_scaled).sum())

NaN em x_test_scaled: 1

Fazendo as previsões e observando os valores

In [221]:
y_svm = best_svm_model.predict(x_test_scaled)

In [222]:
y_svm

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

Adicionando as colunas exigidas para poder submeter na plataforma e salvando

In [223]:
sub_svm = pd.Series(y_svm, index=test_df['PassengerId'], name = 'Survived')

In [224]:
sub_svm

PassengerId
892     0
893     1
894     0
895     0
896     1
       ..
1305    0
1306    1
1307    0
1308    0
1309    0
Name: Survived, Length: 418, dtype: int64

In [226]:
sub_svm.to_csv("svm.csv", header = True)

Correção da atividade:

Sou a tutora Amanda e irei avaliar sua atividade. Fico feliz que tenha dado tudo certo =}

Você soube desenvolver o que aprendeu com a gente sobre a etapa de otimização do modelos. A escolha do algoritmo foi adequada e as técnicas aplicadas contribuíram para aprimorar seu desempenho. A busca pelos melhores hiperparâmetros foi realizada utilizando métodos de otimização, seguida da validação cruzada para verificar a capacidade de generalização do modelo. Além disso, você tratou corretamente o desbalanceamento das classes quando necessário, aplicou a padronização dos dados para os algoritmos sensíveis à escala e treinou o modelo utilizando a divisão entre treino e teste, gerando previsões para avaliar os resultados. O notebook apresenta todas as etapas do processo de maneira clara, justificando as principais decisões adotadas durante a modelagem. Por fim, você enviou o print com a pontuação obtida no Kaggle.

Parabéns pelo excelente trabalho e pela dedicação demonstrada ao longo do desenvolvimento do projeto!

Bons estudos e conte com a gente!